export const testIds = {
  appNav: {
    root: 'app-nav',
    visitsLink: 'app-nav-visits',
    purchasesLink: 'app-nav-purchases',
    menuButton: 'app-nav-menu',
    menuDrawer: 'app-nav-menu-drawer',
    customersLink: 'app-nav-customers',
    materialsLink: 'app-nav-materials',
    servicePricesLink: 'app-nav-service-prices',
    signOutLink: 'app-nav-sign-out',
    signInButton: 'app-nav-sign-in',
  },
  customerForm: {
    root: 'customer-form',
    nameInput: 'customer-form-name',
    commentInput: 'customer-form-comment',
    submitButton: 'customer-form-submit',
  },
  customersList: {
    root: 'customers-list',
    addLink: 'customers-add',
    activeTab: 'customers-status-active',
    archivedTab: 'customers-status-archived',
    row: 'customer-row',
  },
  materialForm: {
    root: 'material-form',
    nameInput: 'material-form-name',
    categorySelect: 'material-form-category',
    unitSelect: 'material-form-unit',
    submitButton: 'material-form-submit',
  },
  materialsList: {
    root: 'materials-list',
    addLink: 'materials-add',
    activeButton: 'materials-status-active',
    archivedButton: 'materials-status-archived',
    categoryToggle: 'materials-category-toggle',
    row: 'material-row',
    stockSummary: 'material-stock-summary',
  },
  purchaseMaterialSelect: {
    select: 'purchase-material-select',
  },
  purchaseForm: {
    root: 'purchase-form',
    materialSummary: 'purchase-form-material-summary',
    countInput: 'purchase-form-count',
    sizeEachInput: 'purchase-form-size-each',
    quantityInput: 'purchase-form-quantity',
    totalQuantityInput: 'purchase-form-total-quantity',
    totalPriceInput: 'purchase-form-total-price',
    dateInput: 'purchase-form-date',
    unitCostPreview: 'purchase-form-unit-cost-preview',
    submitButton: 'purchase-form-submit',
    cancelButton: 'purchase-form-cancel',
  },
  purchasesList: {
    root: 'purchases-list',
    addLink: 'purchases-add',
    row: 'purchase-row',
  },
  purchaseNew: {
    root: 'purchase-new',
    materialPanel: 'purchase-new-material-panel',
    newMaterialToggle: 'purchase-new-material-toggle',
    inlineMaterialPanel: 'purchase-new-inline-material',
    purchasePanel: 'purchase-new-form-panel',
  },
  purchaseDetail: {
    root: 'purchase-detail',
    title: 'purchase-detail-title',
    summary: 'purchase-detail-summary',
    editLink: 'purchase-detail-edit',
    deleteButton: 'purchase-detail-delete',
  },
  visitForm: {
    root: 'visit-form',
    dateInput: 'visit-form-date',
    customerTrigger: 'visit-form-customer-trigger',
    customerDialog: 'visit-form-customer-dialog',
    customerSearchInput: 'visit-form-customer-search',
    customerOption: 'visit-form-customer-option',
    customerCreateButton: 'visit-form-customer-create',
    materialsSection: 'visit-form-materials',
    addMaterialButton: 'visit-form-add-material',
    lineItem: 'visit-form-line-item',
    materialTrigger: 'visit-form-material-trigger',
    materialDialog: 'visit-form-material-dialog',
    materialSearchInput: 'visit-form-material-search',
    materialOption: 'visit-form-material-option',
    materialBuyFirstButton: 'visit-form-material-buy-first',
    materialAmountInput: 'visit-form-material-amount',
    materialUnitCostCaption: 'visit-form-material-unit-cost',
    materialRemoveButton: 'visit-form-material-remove',
    serviceTrigger: 'visit-form-service-trigger',
    serviceDialog: 'visit-form-service-dialog',
    serviceSearchInput: 'visit-form-service-search',
    serviceOption: 'visit-form-service-option',
    priceInput: 'visit-form-price',
    priceSuggestion: 'visit-form-price-suggestion',
    applyPriceSuggestionButton: 'visit-form-apply-price-suggestion',
    noteInput: 'visit-form-note',
  },
  visitsList: {
    root: 'visits-list',
    addLink: 'visits-add',
    row: 'visit-row',
    draftBadge: 'visit-row-draft-badge',
  },
  visitNew: {
    root: 'visit-new',
    form: 'visit-new-form',
    summary: 'visit-new-summary',
    saveDraftButton: 'visit-new-save-draft',
    saveButton: 'visit-new-save',
  },
  visitEdit: {
    root: 'visit-edit',
    form: 'visit-edit-form',
    saveButton: 'visit-edit-save',
  },
  visitDraftEdit: {
    root: 'visit-draft-edit',
    form: 'visit-draft-edit-form',
    discardButton: 'visit-draft-edit-discard',
    saveButton: 'visit-draft-edit-save',
    publishButton: 'visit-draft-edit-publish',
  },
  visitDetail: {
    root: 'visit-detail',
    title: 'visit-detail-title',
    editLink: 'visit-detail-edit',
    deleteButton: 'visit-detail-delete',
    summary: 'visit-detail-summary',
    materials: 'visit-detail-materials',
    materialRow: 'visit-detail-material-row',
    pureLabor: 'visit-detail-pure-labor',
  },
} as const;
