/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppMaterialsRouteImport } from './routes/_app.materials'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app.purchases.index'
import { Route as AppMaterialsIndexRouteImport } from './routes/_app.materials.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppPurchasesNewRouteImport } from './routes/_app.purchases.new'
import { Route as AppPurchasesPurchaseIdRouteImport } from './routes/_app.purchases.$purchaseId'
import { Route as AppMaterialsNewRouteImport } from './routes/_app.materials.new'
import { Route as AppCustomersNewRouteImport } from './routes/_app.customers.new'
import { Route as AppCatalogServicesRouteImport } from './routes/_app.catalog.services'
import { Route as ApiTestPurchasesPurchaseIdRouteImport } from './routes/api.test.purchases.$purchaseId'
import { Route as ApiTestMaterialsMaterialIdRouteImport } from './routes/api.test.materials.$materialId'
import { Route as ApiTestCustomersCustomerIdRouteImport } from './routes/api.test.customers.$customerId'
import { Route as AppPurchasesPurchaseIdEditRouteImport } from './routes/_app.purchases.$purchaseId_.edit'
import { Route as AppMaterialsMaterialIdEditRouteImport } from './routes/_app.materials.$materialId.edit'
import { Route as AppCustomersCustomerIdEditRouteImport } from './routes/_app.customers.$customerId.edit'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppMaterialsIndexRoute = AppMaterialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMaterialsRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppPurchasesPurchaseIdRoute = AppPurchasesPurchaseIdRouteImport.update({
  id: '/$purchaseId',
  path: '/$purchaseId',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppMaterialsNewRoute = AppMaterialsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMaterialsRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppCatalogServicesRoute = AppCatalogServicesRouteImport.update({
  id: '/catalog/services',
  path: '/catalog/services',
  getParentRoute: () => AppRoute,
} as any)
const ApiTestPurchasesPurchaseIdRoute =
  ApiTestPurchasesPurchaseIdRouteImport.update({
    id: '/api/test/purchases/$purchaseId',
    path: '/api/test/purchases/$purchaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTestMaterialsMaterialIdRoute =
  ApiTestMaterialsMaterialIdRouteImport.update({
    id: '/api/test/materials/$materialId',
    path: '/api/test/materials/$materialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTestCustomersCustomerIdRoute =
  ApiTestCustomersCustomerIdRouteImport.update({
    id: '/api/test/customers/$customerId',
    path: '/api/test/customers/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPurchasesPurchaseIdEditRoute =
  AppPurchasesPurchaseIdEditRouteImport.update({
    id: '/$purchaseId_/edit',
    path: '/$purchaseId/edit',
    getParentRoute: () => AppPurchasesRoute,
  } as any)
const AppMaterialsMaterialIdEditRoute =
  AppMaterialsMaterialIdEditRouteImport.update({
    id: '/$materialId/edit',
    path: '/$materialId/edit',
    getParentRoute: () => AppMaterialsRoute,
  } as any)
const AppCustomersCustomerIdEditRoute =
  AppCustomersCustomerIdEditRouteImport.update({
    id: '/$customerId/edit',
    path: '/$customerId/edit',
    getParentRoute: () => AppCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/materials': typeof AppMaterialsRouteWithChildren
  '/purchases': typeof AppPurchasesRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/catalog/services': typeof AppCatalogServicesRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/materials/new': typeof AppMaterialsNewRoute
  '/purchases/$purchaseId': typeof AppPurchasesPurchaseIdRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/materials/': typeof AppMaterialsIndexRoute
  '/purchases/': typeof AppPurchasesIndexRoute
  '/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/materials/$materialId/edit': typeof AppMaterialsMaterialIdEditRoute
  '/purchases/$purchaseId/edit': typeof AppPurchasesPurchaseIdEditRoute
  '/api/test/customers/$customerId': typeof ApiTestCustomersCustomerIdRoute
  '/api/test/materials/$materialId': typeof ApiTestMaterialsMaterialIdRoute
  '/api/test/purchases/$purchaseId': typeof ApiTestPurchasesPurchaseIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/': typeof AppIndexRoute
  '/catalog/services': typeof AppCatalogServicesRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/materials/new': typeof AppMaterialsNewRoute
  '/purchases/$purchaseId': typeof AppPurchasesPurchaseIdRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/customers': typeof AppCustomersIndexRoute
  '/materials': typeof AppMaterialsIndexRoute
  '/purchases': typeof AppPurchasesIndexRoute
  '/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/materials/$materialId/edit': typeof AppMaterialsMaterialIdEditRoute
  '/purchases/$purchaseId/edit': typeof AppPurchasesPurchaseIdEditRoute
  '/api/test/customers/$customerId': typeof ApiTestCustomersCustomerIdRoute
  '/api/test/materials/$materialId': typeof ApiTestMaterialsMaterialIdRoute
  '/api/test/purchases/$purchaseId': typeof ApiTestPurchasesPurchaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/materials': typeof AppMaterialsRouteWithChildren
  '/_app/purchases': typeof AppPurchasesRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/catalog/services': typeof AppCatalogServicesRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/materials/new': typeof AppMaterialsNewRoute
  '/_app/purchases/$purchaseId': typeof AppPurchasesPurchaseIdRoute
  '/_app/purchases/new': typeof AppPurchasesNewRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/materials/': typeof AppMaterialsIndexRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
  '/_app/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/_app/materials/$materialId/edit': typeof AppMaterialsMaterialIdEditRoute
  '/_app/purchases/$purchaseId_/edit': typeof AppPurchasesPurchaseIdEditRoute
  '/api/test/customers/$customerId': typeof ApiTestCustomersCustomerIdRoute
  '/api/test/materials/$materialId': typeof ApiTestMaterialsMaterialIdRoute
  '/api/test/purchases/$purchaseId': typeof ApiTestPurchasesPurchaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-out'
    | '/customers'
    | '/materials'
    | '/purchases'
    | '/sign-in/$'
    | '/catalog/services'
    | '/customers/new'
    | '/materials/new'
    | '/purchases/$purchaseId'
    | '/purchases/new'
    | '/customers/'
    | '/materials/'
    | '/purchases/'
    | '/customers/$customerId/edit'
    | '/materials/$materialId/edit'
    | '/purchases/$purchaseId/edit'
    | '/api/test/customers/$customerId'
    | '/api/test/materials/$materialId'
    | '/api/test/purchases/$purchaseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-out'
    | '/sign-in/$'
    | '/'
    | '/catalog/services'
    | '/customers/new'
    | '/materials/new'
    | '/purchases/$purchaseId'
    | '/purchases/new'
    | '/customers'
    | '/materials'
    | '/purchases'
    | '/customers/$customerId/edit'
    | '/materials/$materialId/edit'
    | '/purchases/$purchaseId/edit'
    | '/api/test/customers/$customerId'
    | '/api/test/materials/$materialId'
    | '/api/test/purchases/$purchaseId'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/sign-out'
    | '/_app/customers'
    | '/_app/materials'
    | '/_app/purchases'
    | '/sign-in/$'
    | '/_app/'
    | '/_app/catalog/services'
    | '/_app/customers/new'
    | '/_app/materials/new'
    | '/_app/purchases/$purchaseId'
    | '/_app/purchases/new'
    | '/_app/customers/'
    | '/_app/materials/'
    | '/_app/purchases/'
    | '/_app/customers/$customerId/edit'
    | '/_app/materials/$materialId/edit'
    | '/_app/purchases/$purchaseId_/edit'
    | '/api/test/customers/$customerId'
    | '/api/test/materials/$materialId'
    | '/api/test/purchases/$purchaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRouteWithChildren
  SignOutRoute: typeof SignOutRoute
  ApiTestCustomersCustomerIdRoute: typeof ApiTestCustomersCustomerIdRoute
  ApiTestMaterialsMaterialIdRoute: typeof ApiTestMaterialsMaterialIdRoute
  ApiTestPurchasesPurchaseIdRoute: typeof ApiTestPurchasesPurchaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials': {
      id: '/_app/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/materials/': {
      id: '/_app/materials/'
      path: '/'
      fullPath: '/materials/'
      preLoaderRoute: typeof AppMaterialsIndexRouteImport
      parentRoute: typeof AppMaterialsRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/purchases/new': {
      id: '/_app/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/purchases/$purchaseId': {
      id: '/_app/purchases/$purchaseId'
      path: '/$purchaseId'
      fullPath: '/purchases/$purchaseId'
      preLoaderRoute: typeof AppPurchasesPurchaseIdRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/materials/new': {
      id: '/_app/materials/new'
      path: '/new'
      fullPath: '/materials/new'
      preLoaderRoute: typeof AppMaterialsNewRouteImport
      parentRoute: typeof AppMaterialsRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/catalog/services': {
      id: '/_app/catalog/services'
      path: '/catalog/services'
      fullPath: '/catalog/services'
      preLoaderRoute: typeof AppCatalogServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/test/purchases/$purchaseId': {
      id: '/api/test/purchases/$purchaseId'
      path: '/api/test/purchases/$purchaseId'
      fullPath: '/api/test/purchases/$purchaseId'
      preLoaderRoute: typeof ApiTestPurchasesPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/materials/$materialId': {
      id: '/api/test/materials/$materialId'
      path: '/api/test/materials/$materialId'
      fullPath: '/api/test/materials/$materialId'
      preLoaderRoute: typeof ApiTestMaterialsMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/customers/$customerId': {
      id: '/api/test/customers/$customerId'
      path: '/api/test/customers/$customerId'
      fullPath: '/api/test/customers/$customerId'
      preLoaderRoute: typeof ApiTestCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/purchases/$purchaseId_/edit': {
      id: '/_app/purchases/$purchaseId_/edit'
      path: '/$purchaseId/edit'
      fullPath: '/purchases/$purchaseId/edit'
      preLoaderRoute: typeof AppPurchasesPurchaseIdEditRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/materials/$materialId/edit': {
      id: '/_app/materials/$materialId/edit'
      path: '/$materialId/edit'
      fullPath: '/materials/$materialId/edit'
      preLoaderRoute: typeof AppMaterialsMaterialIdEditRouteImport
      parentRoute: typeof AppMaterialsRoute
    }
    '/_app/customers/$customerId/edit': {
      id: '/_app/customers/$customerId/edit'
      path: '/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof AppCustomersCustomerIdEditRouteImport
      parentRoute: typeof AppCustomersRoute
    }
  }
}

interface AppCustomersRouteChildren {
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppCustomersCustomerIdEditRoute: typeof AppCustomersCustomerIdEditRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppCustomersCustomerIdEditRoute: AppCustomersCustomerIdEditRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppMaterialsRouteChildren {
  AppMaterialsNewRoute: typeof AppMaterialsNewRoute
  AppMaterialsIndexRoute: typeof AppMaterialsIndexRoute
  AppMaterialsMaterialIdEditRoute: typeof AppMaterialsMaterialIdEditRoute
}

const AppMaterialsRouteChildren: AppMaterialsRouteChildren = {
  AppMaterialsNewRoute: AppMaterialsNewRoute,
  AppMaterialsIndexRoute: AppMaterialsIndexRoute,
  AppMaterialsMaterialIdEditRoute: AppMaterialsMaterialIdEditRoute,
}

const AppMaterialsRouteWithChildren = AppMaterialsRoute._addFileChildren(
  AppMaterialsRouteChildren,
)

interface AppPurchasesRouteChildren {
  AppPurchasesPurchaseIdRoute: typeof AppPurchasesPurchaseIdRoute
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
  AppPurchasesPurchaseIdEditRoute: typeof AppPurchasesPurchaseIdEditRoute
}

const AppPurchasesRouteChildren: AppPurchasesRouteChildren = {
  AppPurchasesPurchaseIdRoute: AppPurchasesPurchaseIdRoute,
  AppPurchasesNewRoute: AppPurchasesNewRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
  AppPurchasesPurchaseIdEditRoute: AppPurchasesPurchaseIdEditRoute,
}

const AppPurchasesRouteWithChildren = AppPurchasesRoute._addFileChildren(
  AppPurchasesRouteChildren,
)

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppMaterialsRoute: typeof AppMaterialsRouteWithChildren
  AppPurchasesRoute: typeof AppPurchasesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCatalogServicesRoute: typeof AppCatalogServicesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppMaterialsRoute: AppMaterialsRouteWithChildren,
  AppPurchasesRoute: AppPurchasesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCatalogServicesRoute: AppCatalogServicesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRouteWithChildren,
  SignOutRoute: SignOutRoute,
  ApiTestCustomersCustomerIdRoute: ApiTestCustomersCustomerIdRoute,
  ApiTestMaterialsMaterialIdRoute: ApiTestMaterialsMaterialIdRoute,
  ApiTestPurchasesPurchaseIdRoute: ApiTestPurchasesPurchaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
